export type StreamFuseSettings = {
  tautulli_url: string;
  tautulli_api_key_set: boolean;
  tautulli_api_key_masked: string | null;
  sftpgo_url: string;
  sftpgo_token_set: boolean;
  sftpgo_token_masked: string | null;
  sftpgo_logs_path: string | null;
  sftpgo_path_mappings: string[];
  samba_enabled: boolean;
  samba_status_json_path: string | null;
  samba_path_mappings: string[];
  unraid_metrics_enabled: boolean;
  unraid_metrics_json_path: string | null;
  use_unraid_totals: boolean;
  energy_tariff_punta_eur_kwh: number;
  energy_tariff_llano_eur_kwh: number;
  energy_tariff_valle_eur_kwh: number;
  energy_tariff_weekend_eur_kwh: number;
  polling_frequency_seconds: number;
  timezone: string;
  media_root_paths: string[];
  preferred_poster_names: string[];
  user_aliases: Record<string, string>;
  placeholder_path: string;
  history_retention_days: number;
  updated_at: string | null;
};

export type StreamFuseSettingsUpdate = {
  tautulli_url?: string;
  tautulli_api_key?: string;
  sftpgo_url?: string;
  sftpgo_token?: string;
  sftpgo_logs_path?: string | null;
  sftpgo_path_mappings?: string[];
  samba_enabled?: boolean;
  samba_status_json_path?: string | null;
  samba_path_mappings?: string[];
  unraid_metrics_enabled?: boolean;
  unraid_metrics_json_path?: string | null;
  use_unraid_totals?: boolean;
  energy_tariff_punta_eur_kwh?: number;
  energy_tariff_llano_eur_kwh?: number;
  energy_tariff_valle_eur_kwh?: number;
  energy_tariff_weekend_eur_kwh?: number;
  polling_frequency_seconds?: number;
  timezone?: string;
  media_root_paths?: string[];
  preferred_poster_names?: string[];
  user_aliases?: Record<string, string>;
  placeholder_path?: string;
  history_retention_days?: number;
};

export type DetectedUserAliasOption = {
  user_name: string;
  alias: string | null;
  session_count: number;
  sources: string[];
};
